<?php
/**
 * Test Script for DSEZA Admin Stats API
 * File: api/test_stats_api.php
 * 
 * This script tests the /api/v1/stats/overview endpoint
 * to ensure it's working correctly with authentication.
 */

// Configuration
$baseUrl = 'http://localhost/api';  // Adjust this to your server URL
$testCredentials = [
    'email' => 'admin@dseza.gov.vn',
    'password' => 'password123'
];

echo "=== DSEZA Admin Stats API Test ===\n\n";

// Function to make HTTP requests
function makeRequest($url, $method = 'GET', $data = null, $headers = []) {
    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    if ($data && ($method === 'POST' || $method === 'PUT')) {
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    }
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error = curl_error($ch);
    
    curl_close($ch);
    
    if ($error) {
        return ['error' => $error, 'http_code' => 0];
    }
    
    return [
        'http_code' => $httpCode,
        'response' => $response,
        'data' => json_decode($response, true)
    ];
}

// Test 1: Login to get JWT token
echo "1. Testing login endpoint...\n";

$loginResult = makeRequest(
    $baseUrl . '/v1/auth/login.php',
    'POST',
    $testCredentials,
    ['Content-Type: application/json']
);

if (isset($loginResult['error'])) {
    echo "   ❌ CURL Error: " . $loginResult['error'] . "\n";
    echo "   🔧 Check if server is running and URL is correct\n\n";
    exit(1);
}

echo "   HTTP Code: " . $loginResult['http_code'] . "\n";

if ($loginResult['http_code'] !== 200) {
    echo "   ❌ Login failed\n";
    echo "   Response: " . $loginResult['response'] . "\n\n";
    exit(1);
}

$loginData = $loginResult['data'];
if (!$loginData || $loginData['status'] !== 'success') {
    echo "   ❌ Login response invalid\n";
    echo "   Response: " . $loginResult['response'] . "\n\n";
    exit(1);
}

$token = $loginData['data']['token'];
echo "   ✅ Login successful\n";
echo "   Token: " . substr($token, 0, 20) . "...\n\n";

// Test 2: Call stats API with valid token
echo "2. Testing stats endpoint with valid token...\n";

$statsResult = makeRequest(
    $baseUrl . '/v1/stats/overview.php',
    'GET',
    null,
    [
        'Content-Type: application/json',
        'Authorization: Bearer ' . $token
    ]
);

echo "   HTTP Code: " . $statsResult['http_code'] . "\n";

if ($statsResult['http_code'] !== 200) {
    echo "   ❌ Stats API failed\n";
    echo "   Response: " . $statsResult['response'] . "\n\n";
} else {
    $statsData = $statsResult['data'];
    if ($statsData && $statsData['status'] === 'success') {
        echo "   ✅ Stats API successful\n";
        echo "   Statistics:\n";
        echo "     - Total News: " . $statsData['data']['totalNews'] . "\n";
        echo "     - Total Events: " . $statsData['data']['totalEvents'] . "\n";
        echo "     - Views This Month: " . $statsData['data']['totalViewsThisMonth'] . "\n";
        echo "     - Active Users This Month: " . $statsData['data']['activeUsersThisMonth'] . "\n";
        echo "   Generated by: " . $statsData['meta']['generated_by'] . "\n";
        echo "   User role: " . $statsData['meta']['user_role'] . "\n\n";
    } else {
        echo "   ❌ Stats API response invalid\n";
        echo "   Response: " . $statsResult['response'] . "\n\n";
    }
}

// Test 3: Call stats API without token (should fail)
echo "3. Testing stats endpoint without token (should fail)...\n";

$noTokenResult = makeRequest(
    $baseUrl . '/v1/stats/overview.php',
    'GET',
    null,
    ['Content-Type: application/json']
);

echo "   HTTP Code: " . $noTokenResult['http_code'] . "\n";

if ($noTokenResult['http_code'] === 401) {
    echo "   ✅ Correctly rejected request without token\n\n";
} else {
    echo "   ❌ Should have returned 401 Unauthorized\n";
    echo "   Response: " . $noTokenResult['response'] . "\n\n";
}

// Test 4: Call stats API with invalid token (should fail)
echo "4. Testing stats endpoint with invalid token (should fail)...\n";

$invalidTokenResult = makeRequest(
    $baseUrl . '/v1/stats/overview.php',
    'GET',
    null,
    [
        'Content-Type: application/json',
        'Authorization: Bearer invalid.token.here'
    ]
);

echo "   HTTP Code: " . $invalidTokenResult['http_code'] . "\n";

if ($invalidTokenResult['http_code'] === 401) {
    echo "   ✅ Correctly rejected request with invalid token\n\n";
} else {
    echo "   ❌ Should have returned 401 Unauthorized\n";
    echo "   Response: " . $invalidTokenResult['response'] . "\n\n";
}

// Test 5: Test with POST method (should fail)
echo "5. Testing stats endpoint with POST method (should fail)...\n";

$postMethodResult = makeRequest(
    $baseUrl . '/v1/stats/overview.php',
    'POST',
    ['test' => 'data'],
    [
        'Content-Type: application/json',
        'Authorization: Bearer ' . $token
    ]
);

echo "   HTTP Code: " . $postMethodResult['http_code'] . "\n";

if ($postMethodResult['http_code'] === 405) {
    echo "   ✅ Correctly rejected POST method\n\n";
} else {
    echo "   ❌ Should have returned 405 Method Not Allowed\n";
    echo "   Response: " . $postMethodResult['response'] . "\n\n";
}

echo "=== Test Summary ===\n";
echo "✅ All tests completed!\n";
echo "📝 Check the output above for any failures.\n";
echo "\n";
echo "🔧 Quick Setup Checklist:\n";
echo "1. Database is running and accessible\n";
echo "2. Run: mysql -u root -p dseza_investment_hub < api/database_setup.sql\n";
echo "3. Run: mysql -u root -p dseza_investment_hub < api/database_setup_extended.sql\n";
echo "4. Update \$baseUrl in this script to match your server\n";
echo "5. Ensure PHP has curl extension enabled\n";
echo "\n";
echo "📚 For more info, see: api/STATS_API_GUIDE.md\n";

?> 